### ISSUE TITLE
"borders" folder CC-2.0 license is not suitable for Debian packaging.

### ISSUE THREAD

**Issue by mzf-guest** [blackfiveimaging/photoprint#8]
The files in the [borders](https://github.com/blackfiveimaging/photoprint/tree/master/borders) folder are licensed under the [CC-2.0](https://github.com/blackfiveimaging/photoprint/blob/master/borders/licence.txt) which is not a valid license for official Debian packaging.

Could you please re-license the files under a newer CC-by version? 3.0 and 4.0 are known to be DFSG-compatible: https://wiki.debian.org/DFSGLicenses#Creative_Commons_Attribution_unported_.28CC-BY.29_v3.0

Thanks!

**Comment by robinsonb5** [comment]
Thanks for pointing out the outdated license - I've just updated it.

**Comment by mzf-guest** [comment]
Thanks!
