### ISSUE TITLE
iccjpeg license violation

### ISSUE THREAD

**Issue by mzf-guest** [blackfiveimaging/photoprint#9]
Photoprint uses part of the [iccjpeg library](https://github.com/blackfiveimaging/library/blob/master/imagesource/iccjpeg.h), which has a [dedicated license](https://github.com/mm2/Little-CMS/blob/master/utils/jpgicc/LICENSE_iccjpeg).

It states that any source distribution or binary distribution should include the iccjpeg license file and displays that "this software is based in part on the work of the Independent JPEG Group".

Unless I'm mistaken, I don't see such mention in Photoprint README or COPYING files. Could you please fix it and check that it's compliant with the Photoprint GPL-2.0 license?

Thanks!

**Comment by robinsonb5** [comment]
Thanks for bringing this to my attention - you're right, I do need to add this.

(The IJG license is GPL-compatible according to https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses)

**Comment by robinsonb5** [comment]
I've just addressed this - thanks for bringing it to my attention.
(Do yell if I've broken anything in the process - I don't currently have a build environment set up with old enough libraries to build this.)

**Comment by bgermann** [comment]
With https://github.com/blackfiveimaging/library/commit/50691f84412802216af926d239e6096d3282e55c this issue can be closed.
